# Generated by Django 5.0.4 on 2024-04-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcmApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcmapiCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'AcmApi_counter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('submitter', models.TextField()),
            ],
            options={
                'db_table': 'quotes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
